name: Publish / beta

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to publish (comma separated: win, mac, linux or "all")'
        default: 'all'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release

      - name: Download Windows Artifacts
        if: contains(github.event.inputs.platforms, 'win') || github.event.inputs.platforms == 'all'
        uses: actions/download-artifact@v4
        with:
          name: installer-windows-latest
          path: ./dist/win

      - name: Download macOS Artifacts
        if: contains(github.event.inputs.platforms, 'mac') || github.event.inputs.platforms == 'all'
        uses: actions/download-artifact@v4
        with:
          name: installer-macos-latest
          path: ./dist/mac

      - name: Download Linux Artifacts
        if: contains(github.event.inputs.platforms, 'linux') || github.event.inputs.platforms == 'all'
        uses: actions/download-artifact@v4
        with:
          name: installer-ubuntu-latest
          path: ./dist/linux

      - name: Configure AWS/S3 Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.UPDATE_FEED_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.UPDATE_FEED_S3_SECRET_KEY }}
          aws-region: us-east-1 # Change to your cloud provider region

      - name: Upload to Beta Bucket
        run: |
          aws s3 sync ./dist s3://${{ secrets.UPDATE_FEED_BUCKET_BETA }}/ --metadata-directive REPLACE --cache-control "max-age=300"

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Beta Publish Status: ${{ job.status }} for platforms: ${{ github.event.inputs.platforms }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_RELEASES }}